# Disable default settings to apply your custom config
use_default_settings: false

# Server configuration
server:
  base_url: "http://35.152.46.49:8888"  # Replace with your IP or domain
  secret_key: "ultrasecretkey"              # Change this to something random/secure
  public_instance: true                     # Allow public use (required for API access)
  limiter: false                            # Set to true to rate-limit public usage
  image_proxy: true                         # Optional: enables image proxying

# User interface options
ui:
  static_use_hash: true                     # Improves caching; recommended

# Redis settings (used for suggestions, caching, etc.)
redis:
  url: redis://redis:6379/0
